spring.application.name=order-service
spring.datasource.url=jdbc:postgresql://localhost:5432/order-service
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8000

payment.vnPay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
payment.vnPay.tmnCode=D8B8653P
payment.vnPay.secretKey=XHK65RKEE9YKDXRHV9RL2XZKO9TIRQ17
payment.vnPay.returnUrl=http://localhost:8000/api/v1/payment/vn-pay-callback
payment.vnPay.version=2.1.0
payment.vnPay.command=pay
payment.vnPay.orderType=other

spring.application.api-prefix=/api/v1